"""empty message

Revision ID: ade64b18492c
Revises: 
Create Date: 2021-11-11 12:19:53.341560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade64b18492c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('colloquial_name', sa.String(length=64), nullable=True),
    sa.Column('waist', sa.String(length=10), nullable=False),
    sa.Column('height', sa.String(length=10), nullable=False),
    sa.Column('bust', sa.String(length=10), nullable=False),
    sa.Column('shoulder_width', sa.String(length=10), nullable=False),
    sa.Column('brand_id', sa.String(length=128), nullable=False),
    sa.Column('style_id', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_Profile_brand_id'), 'Profile', ['brand_id'], unique=False)
    op.create_index(op.f('ix_Profile_bust'), 'Profile', ['bust'], unique=False)
    op.create_index(op.f('ix_Profile_colloquial_name'), 'Profile', ['colloquial_name'], unique=True)
    op.create_index(op.f('ix_Profile_email'), 'Profile', ['email'], unique=True)
    op.create_index(op.f('ix_Profile_height'), 'Profile', ['height'], unique=False)
    op.create_index(op.f('ix_Profile_shoulder_width'), 'Profile', ['shoulder_width'], unique=False)
    op.create_index(op.f('ix_Profile_style_id'), 'Profile', ['style_id'], unique=False)
    op.create_index(op.f('ix_Profile_username'), 'Profile', ['username'], unique=True)
    op.create_index(op.f('ix_Profile_waist'), 'Profile', ['waist'], unique=False)
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brand_brand_name'), 'brand', ['brand_name'], unique=True)
    op.create_table('flask_dance_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('token', sa.JSON(), nullable=False),
    sa.Column('provider', sa.String(length=256), nullable=False),
    sa.Column('provider_user_id', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['Profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flask_dance_oauth')
    op.drop_index(op.f('ix_brand_brand_name'), table_name='brand')
    op.drop_table('brand')
    op.drop_index(op.f('ix_Profile_waist'), table_name='Profile')
    op.drop_index(op.f('ix_Profile_username'), table_name='Profile')
    op.drop_index(op.f('ix_Profile_style_id'), table_name='Profile')
    op.drop_index(op.f('ix_Profile_shoulder_width'), table_name='Profile')
    op.drop_index(op.f('ix_Profile_height'), table_name='Profile')
    op.drop_index(op.f('ix_Profile_email'), table_name='Profile')
    op.drop_index(op.f('ix_Profile_colloquial_name'), table_name='Profile')
    op.drop_index(op.f('ix_Profile_bust'), table_name='Profile')
    op.drop_index(op.f('ix_Profile_brand_id'), table_name='Profile')
    op.drop_table('Profile')
    # ### end Alembic commands ###
