"""empty message

Revision ID: bd43fd1a7ea0
Revises: ade64b18492c
Create Date: 2021-11-16 14:00:22.123853

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bd43fd1a7ea0'
down_revision = 'ade64b18492c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Profile_colloquial_name', table_name='Profile')
    op.drop_column('Profile', 'colloquial_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Profile', sa.Column('colloquial_name', mysql.VARCHAR(length=64), nullable=True))
    op.create_index('ix_Profile_colloquial_name', 'Profile', ['colloquial_name'], unique=False)
    # ### end Alembic commands ###
